---
- name: Install and configure Nginx
  hosts: MonInventaire
  become: true
  tasks:
   -name: Install Nginx
    apt:
      name: nginx
      state: present
      
   -name: start Nginx service
    service:
      name: nginx
      state: started  
